# -*- coding: utf-8 -*-
#
# Copyright (C) 2023-2024 Northwestern University.
#

name: galter-subjects-utils CI

on:
  push:
    branches: master
  pull_request:
    branches: master
  workflow_dispatch:
    inputs:
      reason:
        description: 'Reason'
        required: false
        default: 'Manual trigger'

jobs:
  Tests:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
          python-version: ["3.8", "3.9", "3.10"]
          requirements-level: [pypi]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          pip install .[dev]
          pip freeze

      - name: Run tests
        run: |
          invoke test --no-color
